// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	networkingv1 "k8s.io/api/networking/v1"
)

// NetworkPolicyEgressRuleApplyConfiguration represents a declarative configuration of the NetworkPolicyEgressRule type for use
// with apply.
//
// NetworkPolicyEgressRule wraps the native Kubernetes NetworkPolicyEgressRule.
type NetworkPolicyEgressRuleApplyConfiguration struct {
	networkingv1.NetworkPolicyEgressRule `json:",inline"`
}

// NetworkPolicyEgressRuleApplyConfiguration constructs a declarative configuration of the NetworkPolicyEgressRule type for use with
// apply.
func NetworkPolicyEgressRule() *NetworkPolicyEgressRuleApplyConfiguration {
	return &NetworkPolicyEgressRuleApplyConfiguration{}
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *NetworkPolicyEgressRuleApplyConfiguration) WithPorts(values ...networkingv1.NetworkPolicyPort) *NetworkPolicyEgressRuleApplyConfiguration {
	for i := range values {
		b.NetworkPolicyEgressRule.Ports = append(b.NetworkPolicyEgressRule.Ports, values[i])
	}
	return b
}

// WithTo adds the given value to the To field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the To field.
func (b *NetworkPolicyEgressRuleApplyConfiguration) WithTo(values ...networkingv1.NetworkPolicyPeer) *NetworkPolicyEgressRuleApplyConfiguration {
	for i := range values {
		b.NetworkPolicyEgressRule.To = append(b.NetworkPolicyEgressRule.To, values[i])
	}
	return b
}
