// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	networkingv1 "k8s.io/api/networking/v1"
)

// NetworkPolicyIngressRuleApplyConfiguration represents a declarative configuration of the NetworkPolicyIngressRule type for use
// with apply.
//
// NetworkPolicyIngressRule wraps the native Kubernetes NetworkPolicyIngressRule.
type NetworkPolicyIngressRuleApplyConfiguration struct {
	networkingv1.NetworkPolicyIngressRule `json:",inline"`
}

// NetworkPolicyIngressRuleApplyConfiguration constructs a declarative configuration of the NetworkPolicyIngressRule type for use with
// apply.
func NetworkPolicyIngressRule() *NetworkPolicyIngressRuleApplyConfiguration {
	return &NetworkPolicyIngressRuleApplyConfiguration{}
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *NetworkPolicyIngressRuleApplyConfiguration) WithPorts(values ...networkingv1.NetworkPolicyPort) *NetworkPolicyIngressRuleApplyConfiguration {
	for i := range values {
		b.NetworkPolicyIngressRule.Ports = append(b.NetworkPolicyIngressRule.Ports, values[i])
	}
	return b
}

// WithFrom adds the given value to the From field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the From field.
func (b *NetworkPolicyIngressRuleApplyConfiguration) WithFrom(values ...networkingv1.NetworkPolicyPeer) *NetworkPolicyIngressRuleApplyConfiguration {
	for i := range values {
		b.NetworkPolicyIngressRule.From = append(b.NetworkPolicyIngressRule.From, values[i])
	}
	return b
}
