// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// NetworkIsolationConfigApplyConfiguration represents a declarative configuration of the NetworkIsolationConfig type for use
// with apply.
//
// NetworkIsolationConfig defines network isolation settings for Ray cluster.
// All modes maintain the cluster's ability for intra-node and KubeRay operator communication.
type NetworkIsolationConfigApplyConfiguration struct {
	// Mode controls the security level, all modes maintain the Cluster's
	// ability for intra-node and Kuberay operator communication.
	// - "denyAll": Denies all Ingress and Egress.
	// - "denyAllIngress": Denies all Ingress.
	// - "denyAllEgress": Denies all Egress.
	Mode *string `json:"mode,omitempty"`
	// IngressRules specifies custom ingress rules for the Ray head pod.
	IngressRules []NetworkPolicyIngressRuleApplyConfiguration `json:"ingressRules,omitempty"`
	// EgressRules specifies custom egress rules for the Ray head pod.
	EgressRules []NetworkPolicyEgressRuleApplyConfiguration `json:"egressRules,omitempty"`
}

// NetworkIsolationConfigApplyConfiguration constructs a declarative configuration of the NetworkIsolationConfig type for use with
// apply.
func NetworkIsolationConfig() *NetworkIsolationConfigApplyConfiguration {
	return &NetworkIsolationConfigApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *NetworkIsolationConfigApplyConfiguration) WithMode(value string) *NetworkIsolationConfigApplyConfiguration {
	b.Mode = &value
	return b
}

// WithIngressRules adds the given value to the IngressRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IngressRules field.
func (b *NetworkIsolationConfigApplyConfiguration) WithIngressRules(values ...*NetworkPolicyIngressRuleApplyConfiguration) *NetworkIsolationConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithIngressRules")
		}
		b.IngressRules = append(b.IngressRules, *values[i])
	}
	return b
}

// WithEgressRules adds the given value to the EgressRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EgressRules field.
func (b *NetworkIsolationConfigApplyConfiguration) WithEgressRules(values ...*NetworkPolicyEgressRuleApplyConfiguration) *NetworkIsolationConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEgressRules")
		}
		b.EgressRules = append(b.EgressRules, *values[i])
	}
	return b
}
