// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	networkingv1 "k8s.io/api/networking/v1"
)

// NetworkPolicyEgressRuleApplyConfiguration represents a declarative configuration of the NetworkPolicyEgressRule type for use
// with apply.
//
// NetworkPolicyEgressRule wraps the native Kubernetes NetworkPolicyEgressRule
// with optional metadata fields for debugging and documentation.
type NetworkPolicyEgressRuleApplyConfiguration struct {
	// Name is an optional descriptive name for debugging and logging.
	Name *string `json:"name,omitempty"`
	// Description is an optional longer description for documentation purposes.
	Description *string `json:"description,omitempty"`
	// NetworkPolicyEgressRule embeds the native Kubernetes NetworkPolicyEgressRule type.
	networkingv1.NetworkPolicyEgressRule `json:",inline"`
}

// NetworkPolicyEgressRuleApplyConfiguration constructs a declarative configuration of the NetworkPolicyEgressRule type for use with
// apply.
func NetworkPolicyEgressRule() *NetworkPolicyEgressRuleApplyConfiguration {
	return &NetworkPolicyEgressRuleApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NetworkPolicyEgressRuleApplyConfiguration) WithName(value string) *NetworkPolicyEgressRuleApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *NetworkPolicyEgressRuleApplyConfiguration) WithDescription(value string) *NetworkPolicyEgressRuleApplyConfiguration {
	b.Description = &value
	return b
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *NetworkPolicyEgressRuleApplyConfiguration) WithPorts(values ...networkingv1.NetworkPolicyPort) *NetworkPolicyEgressRuleApplyConfiguration {
	for i := range values {
		b.NetworkPolicyEgressRule.Ports = append(b.NetworkPolicyEgressRule.Ports, values[i])
	}
	return b
}

// WithTo adds the given value to the To field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the To field.
func (b *NetworkPolicyEgressRuleApplyConfiguration) WithTo(values ...networkingv1.NetworkPolicyPeer) *NetworkPolicyEgressRuleApplyConfiguration {
	for i := range values {
		b.NetworkPolicyEgressRule.To = append(b.NetworkPolicyEgressRule.To, values[i])
	}
	return b
}
