// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TLSOptionsApplyConfiguration represents a declarative configuration of the TLSOptions type for use
// with apply.
//
// TLSOptions defines TLS/mTLS encryption settings for Ray cluster communication.
// When present, the operator creates cert-manager resources and injects TLS environment
// variables and volume mounts into Ray head and worker pods.
type TLSOptionsApplyConfiguration struct {
	// Mode controls the security level.
	// - "mTLS": Enables mTLS (Client & Server authentication).
	// - "TLS": Enables standard TLS (Server authentication only).
	Mode *string `json:"mode,omitempty"`
	// SecretName allows "Bring Your Own Certificate".
	// If set, the operator uses this secret for the CA/Cert.
	// If empty, and (m)TLS is enabled, a self-signed CA is generated.
	SecretName *string `json:"secretName,omitempty"`
}

// TLSOptionsApplyConfiguration constructs a declarative configuration of the TLSOptions type for use with
// apply.
func TLSOptions() *TLSOptionsApplyConfiguration {
	return &TLSOptionsApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *TLSOptionsApplyConfiguration) WithMode(value string) *TLSOptionsApplyConfiguration {
	b.Mode = &value
	return b
}

// WithSecretName sets the SecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretName field is set to the value of the last call.
func (b *TLSOptionsApplyConfiguration) WithSecretName(value string) *TLSOptionsApplyConfiguration {
	b.SecretName = &value
	return b
}
